# Deep learning with Pytorch - Module 2
This notebook is based on the course "Deep Learning with Pytorch" by IBM Developer Skills Network. 

## Linear regression in 1D 

Linear regression is a linear approach to modeling the relationship between a scalar response and one or more explanatory variables. In most cases,, it is between the predictor x which is the input, an independent variable and the target y which is the dependent variable.

The goal is to find the best fit line that describes the relationship between x and y. One that fits the equation y = mx + b, where m is the slope (weight) and b is the y-intercept (bias), called linear mapping. This is also called a model.

Once we have the model, we can use it to predict the target value for new input values. The prediction step is called the forward pass. 

In [24]:
# example of linear regression prediction

import torch

w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

def forward(x):
    y = w*x + b
    return y

x = torch.tensor([[1.0]])

yhat = forward(x)

print(yhat) # y hat is the prediction of the model for the chosen input x

tensor([[1.]], grad_fn=<AddBackward0>)


In [25]:
# using Linear class from torch.nn module

from torch.nn import Linear

torch.manual_seed(1) # seed for random number generation for reproducibility

model = Linear(in_features=1, out_features=1, bias = True ) # in_features is the number of input features, out_features is the number of output features

print('Parameters w and b: ', list(model.parameters())) # parameters of the model are the weights and bias

x = torch.tensor([[0.0]]) # input tensor

yhat = model(x) # model is a function that takes input x and returns the prediction yhat

print("the prediction of the model for the input x is: ", yhat)

Parameters w and b:  [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
the prediction of the model for the input x is:  tensor([[-0.4414]], grad_fn=<AddmmBackward0>)


In [26]:
# state_dict() returns a Python dictionary object corresponding to the layers of each parameter tensor
print("Python dictionary: ",model.state_dict())
print("keys: ",model.state_dict().keys())
print("values: {} \n ".format(model.state_dict().values()))


# the keys are the parameter names, and the values are the parameter tensors
print("weight:",model.weight)
print("bias:",model.bias)

Python dictionary:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys:  odict_keys(['weight', 'bias'])
values: odict_values([tensor([[0.5153]]), tensor([-0.4414])]) 
 
weight: Parameter containing:
tensor([[0.5153]], requires_grad=True)
bias: Parameter containing:
tensor([-0.4414], requires_grad=True)


In [27]:
# building custom module for linear regression 

# the module inherits from the nn.Module class

import torch.nn as nn

class LR(nn.Module):
    def __init__(self, input_size, output_size): # super class constructor
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size) 
        
    def forward(self, x): # forward method, behaves like the call method in python, we only use () to apply the model to the input 
        out = self.linear(x)
        return out
    
model = LR(1, 1) # model is an instance of the LR class

print("the parameters: ", list(model.parameters())) # parameters of the model are the weights and bias

print("Linear model: ", model.linear)

x = torch.tensor([[1.0]]) # input tensor

yhat = model(x) # model is a function that takes input x and returns the prediction yhat

print("the prediction of the model for the input x is: ", yhat)

z = torch.tensor([[1.0], [2.0]]) # input tensor

yhat = model(x) # model is a function that takes input x and returns the prediction yhat

print("the prediction of the model for the input z is: ", yhat)

model.state_dict() # state_dict method returns the weights and bias of the model



the parameters:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
Linear model:  Linear(in_features=1, out_features=1, bias=True)
the prediction of the model for the input x is:  tensor([[0.2755]], grad_fn=<AddmmBackward0>)
the prediction of the model for the input z is:  tensor([[0.2755]], grad_fn=<AddmmBackward0>)


OrderedDict([('linear.weight', tensor([[-0.1939]])),
             ('linear.bias', tensor([0.4694]))])